# Generated by Django 6.0.2 on 2026-03-19 03:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True, verbose_name='Sana')),
                ('payment_type', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('transfer', "O'tkazma")], max_length=20, verbose_name="To'lov turi")),
                ('description', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('expense_amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name="Chiqim miqdori (so'm)")),
            ],
            options={
                'verbose_name': 'Chiqim ',
                'verbose_name_plural': 'Chiqimlar ',
                'ordering': ['-date', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True, verbose_name='Sana')),
                ('payment_type', models.CharField(choices=[('cash', 'Naqd'), ('card', 'Karta'), ('transfer', "O'tkazma")], max_length=20, verbose_name="To'lov turi")),
                ('description', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('income_amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name="Kirim miqdori (so'm)")),
            ],
            options={
                'verbose_name': 'Kirim ',
                'verbose_name_plural': 'Kirimlar ',
                'ordering': ['-date', '-created_at'],
                'abstract': False,
            },
        ),
    ]
