# Generated by Django 6.0.3 on 2026-03-13 07:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Chiqim ', 'verbose_name_plural': 'Chiqimlar '},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Kirim ', 'verbose_name_plural': 'Kirimlar '},
        ),
        migrations.AddField(
            model_name='expense',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kim tomonidan yaratilgan'),
        ),
        migrations.AddField(
            model_name='income',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Kim tomonidan yaratilgan'),
        ),
    ]
