# Generated by Django 6.0.3 on 2026-03-13 08:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_expense_options_alter_income_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Tomonidan yaratilgan'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(unique=True, verbose_name='Sana'),
        ),
        migrations.AlterField(
            model_name='income',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Tomonidan yaratilgan'),
        ),
        migrations.AlterField(
            model_name='income',
            name='date',
            field=models.DateField(unique=True, verbose_name='Sana'),
        ),
    ]
