# Generated by Django 6.0.2 on 2026-02-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_worker_status_user_is_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_worker',
            field=models.BooleanField(default=False, help_text='Yangi foydalanuvchi xodim yoki xodim emas.', verbose_name='worker'),
        ),
    ]
