# Generated by Django 4.2 on 2026-03-28 16:24

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.functions.text
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expenses',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True, verbose_name='Sana')),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=20, verbose_name='Umumiy xarajat')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
            ],
            options={
                'verbose_name': 'Xarajat ',
                'verbose_name_plural': 'Xarajatlar ',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Miqdori')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Narxi')),
                ('payment_status', models.CharField(choices=[('unpaid', "To'lanmagan"), ('partial', 'Qisman'), ('paid', "To'langan")], default='unpaid', max_length=10, verbose_name="To'lov holati")),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name="To'langan summa")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
            ],
            options={
                'verbose_name': 'Oziq-ovqat xarajati ',
                'verbose_name_plural': 'Oziq-ovqat xarajatlari ',
            },
        ),
        migrations.CreateModel(
            name='FoodProducts',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('food_product_name', models.CharField(max_length=255, verbose_name='Oziq-ovqat nomi')),
                ('measurement_unit', models.CharField(blank=True, max_length=64, verbose_name="O'lchov birligi")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
            ],
            options={
                'verbose_name': 'Oziq-ovqat ',
                'verbose_name_plural': 'Oziq-ovqatlar ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OtherExpenseItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Miqdori')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Narxi')),
                ('payment_status', models.CharField(choices=[('unpaid', "To'lanmagan"), ('partial', 'Qisman'), ('paid', "To'langan")], default='unpaid', max_length=10, verbose_name="To'lov holati")),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name="To'langan summa")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
            ],
            options={
                'verbose_name': 'Boshqa xarajat ',
                'verbose_name_plural': 'Boshqa xarajatlar ',
            },
        ),
        migrations.CreateModel(
            name='OtherExpenseTypes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expense_type_name', models.CharField(max_length=255, verbose_name='Xarajat turi nomi')),
                ('measurement_unit', models.CharField(blank=True, max_length=64, verbose_name="O'lchov birligi")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
            ],
            options={
                'verbose_name': 'Boshqa xarajat turi ',
                'verbose_name_plural': 'Boshqa xarajat turlari ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RawItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Miqdori')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Narxi')),
                ('payment_status', models.CharField(choices=[('unpaid', "To'lanmagan"), ('partial', 'Qisman'), ('paid', "To'langan")], default='unpaid', max_length=10, verbose_name="To'lov holati")),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name="To'langan summa")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
            ],
            options={
                'verbose_name': 'Xom-ashyo xarajati ',
                'verbose_name_plural': 'Xom-ashyo xarajatlari ',
            },
        ),
        migrations.CreateModel(
            name='RawMaterials',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('raw_material_name', models.CharField(max_length=255, verbose_name='Xom-ashyo nomi')),
                ('measurement_unit', models.CharField(blank=True, max_length=64, verbose_name="O'lchov birligi")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
            ],
            options={
                'verbose_name': 'Xom-ashyo ',
                'verbose_name_plural': 'Xom-ashyolar ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='rawmaterials',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('raw_material_name')), name='expenses_rawmaterials_name_unique_ci', violation_error_message='Bu xom-ashyo nomi allaqachon mavjud.'),
        ),
        migrations.AddField(
            model_name='rawitem',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_items', to='expenses.expenses'),
        ),
        migrations.AddField(
            model_name='rawitem',
            name='raw_material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.rawmaterials', verbose_name='Xom-ashyo nomi'),
        ),
        migrations.AddConstraint(
            model_name='otherexpensetypes',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('expense_type_name')), name='expenses_otherexpensetypes_name_unique_ci', violation_error_message='Bu xarajat turi nomi allaqachon mavjud.'),
        ),
        migrations.AddField(
            model_name='otherexpenseitem',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='other_items', to='expenses.expenses'),
        ),
        migrations.AddField(
            model_name='otherexpenseitem',
            name='expense_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.otherexpensetypes', verbose_name='Xarajat turi'),
        ),
        migrations.AddConstraint(
            model_name='foodproducts',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('food_product_name')), name='expenses_foodproducts_name_unique_ci', violation_error_message='Bu oziq-ovqat nomi allaqachon mavjud.'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='expense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to='expenses.expenses'),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='food_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expenses.foodproducts', verbose_name='Oziq-ovqat nomi'),
        ),
    ]
