# Generated by Django 6.0.3 on 2026-03-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name="To'langan summa"),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', "To'lanmagan"), ('partial', 'Qisman'), ('paid', "To'langan")], default='unpaid', max_length=10, verbose_name="To'lov holati"),
        ),
        migrations.AddField(
            model_name='rawitem',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name="To'langan summa"),
        ),
        migrations.AddField(
            model_name='rawitem',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', "To'lanmagan"), ('partial', 'Qisman'), ('paid', "To'langan")], default='unpaid', max_length=10, verbose_name="To'lov holati"),
        ),
    ]
