# Generated by Django 6.0.2 on 2026-03-25 07:54

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='foodproducts',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('food_product_name')), name='expenses_foodproducts_name_unique_ci', violation_error_message='Bu oziq-ovqat nomi allaqachon mavjud.'),
        ),
        migrations.AddConstraint(
            model_name='otherexpensetypes',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('expense_type_name')), name='expenses_otherexpensetypes_name_unique_ci', violation_error_message='Bu xarajat turi nomi allaqachon mavjud.'),
        ),
        migrations.AddConstraint(
            model_name='rawmaterials',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower(django.db.models.functions.text.Trim('raw_material_name')), name='expenses_rawmaterials_name_unique_ci', violation_error_message='Bu xom-ashyo nomi allaqachon mavjud.'),
        ),
    ]
