# Generated by Django 6.0.3 on 2026-03-16 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0003_fooditem_paid_amount_fooditem_payment_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fooditem',
            options={'verbose_name': 'Oziq-ovqat xarajati ', 'verbose_name_plural': 'Oziq-ovqat xarajatlari '},
        ),
        migrations.AlterModelOptions(
            name='rawitem',
            options={'verbose_name': 'Xom-ashyo xarajati ', 'verbose_name_plural': 'Xom-ashyo xarajatlari '},
        ),
    ]
