# Generated by Django 6.0.3 on 2026-03-16 05:52

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False, verbose_name='Sana')),
            ],
            options={
                'verbose_name': 'Statistika',
                'verbose_name_plural': 'Statistika',
                'managed': False,
            },
        ),
        migrations.AlterField(
            model_name='dailyfinancereport',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name='Balans'),
        ),
        migrations.AlterField(
            model_name='dailyfinancereport',
            name='total_closed_sales',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name='Yopilgan zakaz savdosi'),
        ),
        migrations.AlterField(
            model_name='dailyfinancereport',
            name='total_earned_salary',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name='Ishchilar ishlab topgan summa'),
        ),
        migrations.AlterField(
            model_name='dailyfinancereport',
            name='total_expenses',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=20, verbose_name='Umumiy xarajat'),
        ),
    ]
