# Generated by Django 6.0.2 on 2026-02-20 12:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255, verbose_name='Имя и Фамилия')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='Должность')),
                ('salary_type', models.CharField(blank=True, max_length=50, verbose_name='Тип зарплаты')),
                ('base_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Базовая зарплата')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL, verbose_name='Имя пользователя')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True, verbose_name='Дата')),
                ('total_earned_salary', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Общая заработанная зарплата')),
                ('total_paid_salary', models.DecimalField(decimal_places=2, default=0, max_digits=20, verbose_name='Общая выплаченная зарплата')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создал')),
            ],
            options={
                'verbose_name': 'Зарплата',
                'verbose_name_plural': 'Зарплаты',
                'ordering': ['-date', '-created_at'],
                'unique_together': {('created_by', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SalaryItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('earned_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('earned_note', models.CharField(blank=True, max_length=255, null=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('paid_note', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_items', to='salary.employee')),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_items', to='salary.salary')),
            ],
            options={
                'verbose_name': 'Элемент зарплаты',
                'verbose_name_plural': 'Элементы зарплаты',
                'ordering': ['-salary__date', 'created_at'],
            },
        ),
    ]
