# Generated by Django 6.0.3 on 2026-03-11 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salary',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Ish haqi ', 'verbose_name_plural': 'Ish haqi '},
        ),
        migrations.AlterModelOptions(
            name='salaryitem',
            options={'ordering': ['-salary__date', 'created_at'], 'verbose_name': 'Ishchi ish haqi ', 'verbose_name_plural': 'Ishchilar ish haqi '},
        ),
    ]
