# Generated by Django 6.0.2 on 2026-02-22 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0002_alter_salaryitem_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salary',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Oylik maosh', 'verbose_name_plural': 'Oylik maoshlar'},
        ),
    ]
