# Generated by Django 6.0.2 on 2026-02-20 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('salary', '0003_remove_salary_earned_amount_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['created_at'], 'verbose_name': 'Работник', 'verbose_name_plural': 'Работники'},
        ),
        migrations.AlterModelOptions(
            name='salary',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Зарплата', 'verbose_name_plural': 'Зарплаты'},
        ),
        migrations.AlterModelOptions(
            name='salaryitem',
            options={'ordering': ['-salary__date', 'created_at'], 'verbose_name': 'Элемент зарплаты', 'verbose_name_plural': 'Элементы зарплаты'},
        ),
        migrations.AlterField(
            model_name='salary',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
