# Generated by Django 4.2 on 2026-03-28 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Yaratgan foydalanuvchi'),
        ),
        migrations.CreateModel(
            name='OpenSaleItem',
            fields=[
            ],
            options={
                'verbose_name': 'Yopilmagan zakaz',
                'verbose_name_plural': 'Yopilmagan zakazlar',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sales.saleitem',),
        ),
        migrations.CreateModel(
            name='UnpaidSaleItem',
            fields=[
            ],
            options={
                'verbose_name': "To'lanmagan zakaz",
                'verbose_name_plural': "To'lanmagan zakazlar",
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('sales.saleitem',),
        ),
    ]
