# Generated by Django 6.0.2 on 2026-02-24 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='order_status',
            field=models.CharField(choices=[('open', "Yo'q"), ('closed', 'Ha')], default='open', max_length=10, verbose_name='Zakaz yopilganmi'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', "Yo'q"), ('partial', 'Qisman'), ('paid', 'Ha')], default='unpaid', max_length=10, verbose_name="To'lov holati"),
        ),
    ]
