# Generated by Django 6.0.2 on 2026-02-14 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_saleitem_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=15, null=True),
        ),
    ]
