# Generated by Django 6.0.3 on 2026-03-16 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_saleitem_buyers_paid_alter_saleitem_order_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='saleitem',
            options={'verbose_name': 'Zakaz mahsuloti ', 'verbose_name_plural': 'Zakaz mahsulotlari '},
        ),
    ]
